### ISSUE TITLE
WCAG: Multiple ways to navigate to content

### ISSUE THREAD

**Issue by knut-hufthammer** [miles-no/miles_no#23]
Currently, we only have one way of navigating to content on the website, this is through the menu. WCAG AA requires us to have at least two different methods for navigating to content. 

Other alternatives could be:
- Search
- Website map (Nettstedskart?) 

https://www.uutilsynet.no/veiledning/navigasjonsmetoder/217

**Comment by knut-hufthammer** [comment]
This was suggested by Paal Kristian back in August. It was also suggested that we add a "search field" during one of our status meeting. Maybe we can look into this now.

**Comment by mahdiislam** [comment]
Use https://seositecheckup.com/tools/sitemap-test to determine sitemap. For the new site, it's under: https://www.miles.no/newsite/sitemap_index.xml
